### ISSUE TITLE
Ik ben hier toch niet zo blij mee, doe maar opnieuw

### ISSUE THREAD

**Issue by clarkFransje** [Mjaerten/ProftaakSemester2#2]
Ik ben hier toch niet zo blij mee, doe maar opnieuw

_Originally posted by @PlunkyPoop in https://github.com/Mjaerten/ProftaakSemester2/issues/1#issuecomment-1032558943_

**Comment by clarkFransje** [comment]
het probleem is dat iedereen dit kan zien

**Comment by clarkFransje** [comment]
dit moeten we fixen door gebruik te maken van gitignore!

**Comment by PlunkyPoop** [comment]
👍
